-- ====================================================================
-- PARTE 1: SCRIPT DE DATOS SEMILLA PARA NATURART FOODS (THICK DATABASE)
-- ====================================================================
-- Este script inserta datos maestros iniciales garantizando la integridad
-- referencial y preparando el terreno para las transacciones (checkout).
-- 
-- Ejecutar en Oracle con el usuario de QYT (ej. ADMDESAR).
-- ====================================================================

-- 1. EMPRESA (Raíz de la arquitectura)
INSERT INTO EMPRESA (
    EMP_RUC, EMP_DESCRIPCION, EMP_DIRECCION, EMP_TELEFONO, 
    EMP_CORREO, EMP_REPRESENTANTE, EMP_IVA, EMP_PRC_UTILIDAD, 
    EMP_PRC_COM_VENTA, EMP_CODIGO_SRI
) VALUES (
    '1790000000001', 'NATURART FOODS S.A.', 'AV. PRINCIPAL QUITO', '022000000', 
    'admin@naturart.com', 'JUAN PEREZ', 0.15, 0.30, 0.05, 'SRI-001'
);

-- 2. PROVINCIA
INSERT INTO PROVINCIA (PRO_CODIGO, PRO_DESCRIPCION) 
VALUES ('17', 'PICHINCHA');

-- 3. CIUDAD (Requiere PROVINCIA)
INSERT INTO CIUDAD (CIU_CODIGO, PRO_CODIGO, CIU_NOMBRE) 
VALUES ('UIO1', '17', 'QUITO');

-- 4. SUCURSAL (Requiere EMPRESA y CIUDAD)
INSERT INTO SUCURSAL (
    SUC_CODIGO, EMP_RUC, CIU_CODIGO, SUC_DESCRIPCION, 
    SUC_DIRECCION, SUC_TELEFONO, SUC_CORREO, SUC_RESPONSABLE, 
    SUC_CODIGO_SRI, SUC_NUMFACINI
) VALUES (
    'WEB', '1790000000001', 'UIO1', 'SUCURSAL VIRTUAL WEB', 
    'CALLE VIRTUAL', '0999999999', 'web@naturart.com', 'SISTEMA', 
    'SRI-WEB-001', '001-001-000000001'
);

-- 5. BODEGA (Requiere SUCURSAL)
INSERT INTO BODEGA (BOD_CODIGO, SUC_CODIGO, BOD_DESCRIPCION) 
VALUES ('SUC1', 'WEB', 'BODEGA PRINCIPAL E-COMMERCE');

-- 6. CARGO
INSERT INTO CARGO (CRG_CODIGO, CRG_DESCRIPCION, CRG_COMISION) 
VALUES ('SYS', 'SISTEMA AUTOMATICO', 'N');

-- 7. DEPARTAMENTO (Requiere EMPRESA)
INSERT INTO DEPARTAMENTO (DPT_CODIGO, EMP_RUC, DPT_DESCRIPCION) 
VALUES ('IT01', '1790000000001', 'TECNOLOGIA E-COMMERCE');

-- 8. EMPLEADO (Requiere EMPRESA, SUCURSAL, CIUDAD, CARGO, DEPARTAMENTO)
INSERT INTO EMPLEADO (
    PLE_CEDULA, EMP_RUC, SUC_CODIGO, CIU_CODIGO, CRG_CODIGO, 
    DPT_CODIGO, PLE_CODIGO, PLE_NOMBRE, PLE_DIRECCION, 
    PLE_TELEFONO, PLE_CARGO, PLE_CORREO, PLE_SUELDO
) VALUES (
    'SISTEMA', '1790000000001', 'WEB', 'UIO1', 'SYS', 
    'IT01', 'EMP-SYS-001', 'BOT SISTEMA WEB', 'VIRTUAL', 
    '0000000000', 'BOT', 'bot@naturart.com', 0
);

-- 9. CATEGORIA (Ajustado a los requerimientos de la tabla real)
INSERT INTO CATEGORIA (CAT_CODIGO, NOMBRE) 
VALUES ('C001', 'FRUTOS SECOS');

-- 10. UNIDAD_MEDIDA
INSERT INTO UNIDAD_MEDIDA (UNM_CODIGO, UNM_DESCRIPCION) 
VALUES ('KG01', 'KILOGRAMOS');

-- 11. PRODUCTO (Requiere UNIDAD_MEDIDA y CATEGORIA)
-- Longitud de PRD_CODIGO reducida a max 10 caracteres por restriccion del TRG_REPLICACION_PRODUCTO
INSERT INTO PRODUCTO (
    PRD_CODIGO, UNM_CODIGO, CAT_CODIGO, PRD_CODIGO_BARRA, 
    PRD_DESCRIPCION, PRD_PRECIO_COMPRA, PRD_PRECIO_VENTA, 
    PRD_PRECIO_VEN_ANT, PRD_PAGA_IVA, PRD_STOCK_MIN, PRD_METODO_VALORA
) VALUES (
    'PRD-ALM-01', 'KG01', 'C001', '1234567890', 
    'ALMENDRAS TOSTADAS 1KG', 10.00, 15.00, 15.00, 'N', 10, 'F'
);

-- 12. PROD_BODGA (Stock inicial - Requiere PRODUCTO y BODEGA)
INSERT INTO PROD_BODGA (PRD_CODIGO, BOD_CODIGO, PRB_EXISTENCIA) 
VALUES ('PRD-ALM-01', 'SUC1', 100);

-- 13. CLIENTE (Requiere EMPRESA)
INSERT INTO CLIENTE (
    CLI_CI_RUC, EMP_RUC, CLI_NOMBRE, CLI_DIRECCION, 
    CLI_TELEFONO, CLI_CORREO, CLI_CODIGO_POSTAL
) VALUES (
    '1700000000', '1790000000001', 'CLIENTE DE PRUEBA', 'CALLE FALSA 123', 
    '0999999999', 'cliente@prueba.com', '170101'
);

-- 14. USUARIO_A (Requiere CLIENTE)
INSERT INTO USUARIO_A (URA_USUARIO, CLI_CI_RUC, URA_CLAVE) 
VALUES ('CLIENTE1', '1700000000', '123456');

COMMIT;
