CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_ROL_CLIENTE(
    p_id IN VARCHAR2,
    p_rol IN VARCHAR2
)
AS
BEGIN
    UPDATE CLIENTE 
    SET CLI_ROL = p_rol 
    WHERE CLI_CI_RUC = p_id;
    COMMIT;
END;
