-- ============================================================================
-- 2. CREACIÓN DE TABLAS DE DIMENSIONES
-- ============================================================================

-- Dimensión Cliente
CREATE TABLE DIM_CLIENTE (
   CLI_ID            VARCHAR2(15) PRIMARY KEY,
   CLI_NOMBRE        VARCHAR2(100),
   CLI_DIRECCION     VARCHAR2(255),
   CLI_TELEFONO      VARCHAR2(15),
   CLI_CORREO        VARCHAR2(100)
) TABLESPACE DATOS;

-- Dimensión Producto (Incluye la descripción de la categoría desnormalizada)
CREATE TABLE DIM_PRODUCTO (
   PRD_ID            VARCHAR2(10) PRIMARY KEY,
   PRD_NOMBRE        VARCHAR2(100),
   PRD_PRECIO        NUMBER(12,2),
   CAT_NOMBRE        VARCHAR2(100) -- Atributo desnormalizado de la tabla CATEGORIA
) TABLESPACE DATOS;

-- Dimensión Tiempo
CREATE TABLE DIM_TIEMPO (
   FECHA             DATE PRIMARY KEY,
   DIA               NUMBER,
   MES               NUMBER,
   ANIO              NUMBER,
   DIA_SEMANA        VARCHAR2(20),
   TEMPORADA         VARCHAR2(30) -- Lógica de negocio analítica
) TABLESPACE DATOS;

-- ============================================================================
-- 3. CREACIÓN DE LA TABLA DE HECHOS CENTRAL
-- ============================================================================
CREATE TABLE HECHOS_VENTAS (
   HECHO_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   CLI_ID            VARCHAR2(15),
   PRD_ID            VARCHAR2(10),
   FECHA             DATE,
   FACTURA_NUMERO    NUMBER,
   CANTIDAD_VENDIDA  NUMBER(12,2),
   PRECIO_UNITARIO   NUMBER(12,2),
   MONTO_TOTAL_LINEA NUMBER(12,2), -- Cantidad * Precio
   FOREIGN KEY (CLI_ID) REFERENCES DIM_CLIENTE(CLI_ID),
   FOREIGN KEY (PRD_ID) REFERENCES DIM_PRODUCTO(PRD_ID),
   FOREIGN KEY (FECHA) REFERENCES DIM_TIEMPO(FECHA)
) TABLESPACE DATOS;

-- ============================================================================
-- 4. OPTIMIZACIÓN MEDIANTE ÍNDICES ANALÍTICOS
-- ============================================================================
CREATE INDEX IDX_FACT_VENTA_CLI ON HECHOS_VENTAS (CLI_ID) TABLESPACE INDICES;
CREATE INDEX IDX_FACT_VENTA_PRD ON HECHOS_VENTAS (PRD_ID) TABLESPACE INDICES;
CREATE INDEX IDX_FACT_VENTA_FEC ON HECHOS_VENTAS (FECHA) TABLESPACE INDICES;









CREATE OR REPLACE PROCEDURE sp_ejecutar_etl_facturacion AS
BEGIN
    -- 1. CARGA DE LA DIMENSIÓN TIEMPO (Extracción y transformación de fechas de factura)
    INSERT INTO DIM_TIEMPO (FECHA, DIA, MES, ANIO, DIA_SEMANA, TEMPORADA)
    SELECT DISTINCT 
        FAC_FECHA,
        EXTRACT(DAY FROM FAC_FECHA),
        EXTRACT(MONTH FROM FAC_FECHA),
        EXTRACT(YEAR FROM FAC_FECHA),
        TO_CHAR(FAC_FECHA, 'Day', 'NLS_DATE_LANGUAGE = SPANISH'),
        CASE 
            WHEN EXTRACT(MONTH FROM FAC_FECHA) = 12 THEN 'Navidad y Fin de Año'
            WHEN EXTRACT(MONTH FROM FAC_FECHA) IN (6, 7, 8) THEN 'Vacaciones de Verano'
            WHEN EXTRACT(MONTH FROM FAC_FECHA) = 5 THEN 'Temporada Día de la Madre'
            ELSE 'Temporada Regular'
        END AS TEMPORADA
    FROM FACTURA@link_transaccional_oltp
    WHERE FAC_FECHA NOT IN (SELECT FECHA FROM DIM_TIEMPO);

    -- 2. CARGA DE LA DIMENSIÓN CLIENTE
    INSERT INTO DIM_CLIENTE (CLI_ID, CLI_NOMBRE, CLI_DIRECCION, CLI_TELEFONO, CLI_CORREO)
    SELECT CLI_CI_RUC, CLI_NOMBRE, CLI_DIRECCION, CLI_TELEFONO, CLI_CORREO
    FROM CLIENTE@link_transaccional_oltp
    WHERE CLI_CI_RUC NOT IN (SELECT CLI_ID FROM DIM_CLIENTE);

    -- 3. CARGA DE LA DIMENSIÓN PRODUCTO (Unión transaccional desnormalizada con Categoría)
    INSERT INTO DIM_PRODUCTO (PRD_ID, PRD_NOMBRE, PRD_PRECIO, CAT_NOMBRE)
    SELECT 
        p.PRD_CODIGO, 
        p.PRD_NOMBRE, 
        p.PRD_PRECIO, 
        NVL(c.NOMBRE, NVL(p.PRD_CATEGORIA, 'SIN CATEGORIA')) AS CAT_NOMBRE
    FROM PRODUCTO@link_transaccional_oltp p
    LEFT JOIN CATEGORIA@link_transaccional_oltp c ON p.CAT_CODIGO = c.CAT_CODIGO
    WHERE p.PRD_CODIGO NOT IN (SELECT PRD_ID FROM DIM_PRODUCTO);

    -- 4. CARGA DE LA TABLA DE HECHOS (Consolidación de Facturas y sus Detalles)
    INSERT INTO HECHOS_VENTAS (CLI_ID, PRD_ID, FECHA, FACTURA_NUMERO, CANTIDAD_VENDIDA, PRECIO_UNITARIO, MONTO_TOTAL_LINEA)
    SELECT 
        f.CLI_CI_RUC,
        df.PRD_CODIGO,
        f.FAC_FECHA,
        f.FAC_NUMERO,
        df.DFA_CANTIDAD,
        df.DFA_PRECIO_UNI,
        (df.DFA_CANTIDAD * df.DFA_PRECIO_UNI) AS MONTO_TOTAL_LINEA
    FROM FACTURA@link_transaccional_oltp f
    JOIN DETALLE_FACTURA@link_transaccional_oltp df ON f.FAC_NUMERO = df.FAC_NUMERO
    WHERE NOT EXISTS (
        SELECT 1 FROM HECHOS_VENTAS h 
        WHERE h.FACTURA_NUMERO = f.FAC_NUMERO AND h.PRD_ID = df.PRD_CODIGO
    );

    COMMIT;
END;
/





SELECT 
    t.ANIO,
    t.TEMPORADA,
    p.CAT_NOMBRE AS CATEGORIA,
    p.PRD_NOMBRE AS PRODUCTO,
    c.CLI_NOMBRE AS CLIENTE,
    SUM(h.CANTIDAD_VENDIDA) AS UNIDADES_VENDIDAS,
    SUM(h.MONTO_TOTAL_LINEA) AS INGRESOS_TOTALES
FROM HECHOS_VENTAS h
JOIN DIM_CLIENTE c  ON h.CLI_ID = c.CLI_ID
JOIN DIM_PRODUCTO p ON h.PRD_ID = p.PRD_ID
JOIN DIM_TIEMPO t   ON h.FECHA = t.FECHA
GROUP BY t.ANIO, t.TEMPORADA, p.CAT_NOMBRE, p.PRD_NOMBRE, c.CLI_NOMBRE
ORDER BY INGRESOS_TOTALES DESC;