-- ==============================================================
-- ACTUALIZACIONES EN QYT (192.168.56.81)
-- ==============================================================

-- 1. Actualizar PRODUCTO (Manejando el cambio de tipo de dato para categoría)
ALTER TABLE PRODUCTO ADD (
    fecha_creacion DATE DEFAULT SYSDATE,
    PRD_IMAGEN_URL VARCHAR2(255),
    PRD_DESCRIPCION VARCHAR2(1000),
    PRD_DESCUENTO_PCT NUMBER(5,2) DEFAULT 0
);

-- NOTA: Como PRD_CATEGORIA era NUMBER(10) en el script original, usamos MODIFY 
-- para adaptarlo a la nueva estructura.
ALTER TABLE PRODUCTO MODIFY (PRD_CATEGORIA VARCHAR2(50));

-- 2. Crear tabla CATEGORIAS
CREATE TABLE CATEGORIAS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) UNIQUE NOT NULL
) TABLESPACE DATA;

-- 3. Insertar categorías iniciales (Si existen)
INSERT INTO CATEGORIAS (NOMBRE) 
SELECT DISTINCT PRD_CATEGORIA FROM PRODUCTO WHERE PRD_CATEGORIA IS NOT NULL;
COMMIT;

-- 4. Crear tabla FAVORITOS en QYT
CREATE TABLE FAVORITOS (
    cli_ced_ruc VARCHAR2(13) NOT NULL,
    prd_codigo VARCHAR2(10) NOT NULL,
    fecha_agregado DATE DEFAULT SYSDATE,
    CONSTRAINT pk_favoritos PRIMARY KEY (cli_ced_ruc, prd_codigo),
    -- FK Local a Producto
    CONSTRAINT fk_fav_producto FOREIGN KEY (prd_codigo) REFERENCES PRODUCTO(PRD_CODIGO) ON DELETE CASCADE
) TABLESPACE DATA;
/

-- 5. Disparador para simular el Foreign Key de CLIENTE a través del DB Link
CREATE OR REPLACE TRIGGER TIB_FAVORITOS_CLIENTE
BEFORE INSERT OR UPDATE OF cli_ced_ruc ON FAVORITOS
FOR EACH ROW
DECLARE
    dummy INTEGER;
    found BOOLEAN;
    -- Validamos contra la tabla remota en Guayas
    CURSOR c_cliente(v_cedula VARCHAR2) IS
        SELECT 1 FROM CLIENTE@link_contingencia_gyq 
        WHERE CLI_CED_RUC = v_cedula;
BEGIN
    IF :new.cli_ced_ruc IS NOT NULL THEN
        OPEN c_cliente(:new.cli_ced_ruc);
        FETCH c_cliente INTO dummy;
        found := c_cliente%FOUND;
        CLOSE c_cliente;
        
        IF NOT found THEN
            raise_application_error(-20010, 'Violación de Integridad: El cliente no existe en el nodo GYQ (Guayas). No se puede agregar a favoritos.');
        END IF;
    END IF;
END;
/