CREATE OR REPLACE VIEW vw_historial_mis_pedidos AS
SELECT
    F.FAC_NUMERO, 
    F.FAC_FECHA, 
    F.FAC_ESTADO, 
    D.PRD_CODIGO, 
    D.DFA_CANTIDAD, 
    D.DFA_PRECIO_UNI,
    P.PRD_NOMBRE,
    F.CLI_CI_RUC AS IDENTIFICADOR_SESION
FROM FACTURA F
LEFT JOIN DETALLE_FACTURA D ON F.FAC_NUMERO = D.FAC_NUMERO
LEFT JOIN PRODUCTO P ON D.PRD_CODIGO = P.PRD_CODIGO
