-- Vistas para Thick Database de Facturación

CREATE OR REPLACE VIEW vw_historial_pedidos AS
SELECT F.FAC_NUMERO, F.FAC_FECHA, F.FAC_ESTADO, F.CLI_CI_RUC,
       D.PRD_CODIGO, D.DFA_CANTIDAD, D.DFA_PRECIO_UNI,
       V.PRD_NOMBRE AS TITULO, V.PRD_IMAGEN_URL AS IMAGEN_URL
FROM FACTURA F
LEFT JOIN DETALLE_FACTURA D ON F.FAC_NUMERO = D.FAC_NUMERO
LEFT JOIN PRODUCTO V ON D.PRD_CODIGO = V.PRD_CODIGO;

CREATE OR REPLACE VIEW vw_admin_pedidos AS
SELECT 
  F.FAC_NUMERO AS id, 
  C.CLI_NOMBRE AS cliente, 
  C.CLI_CORREO AS correo, 
  F.FAC_FECHA AS fecha, 
  F.FAC_ESTADO AS estado,
  NVL(SUM(D.DFA_CANTIDAD * D.DFA_PRECIO_UNI), 0) AS total
FROM FACTURA F
JOIN CLIENTE C ON F.CLI_CI_RUC = C.CLI_CI_RUC
LEFT JOIN DETALLE_FACTURA D ON F.FAC_NUMERO = D.FAC_NUMERO
GROUP BY F.FAC_NUMERO, C.CLI_NOMBRE, C.CLI_CORREO, F.FAC_FECHA, F.FAC_ESTADO;
